name: add-participant-asana-task
on:
  issue_comment:
    types: [created]

concurrency:
  group: asana-${{ github.event.issue.number }}

jobs:
  add-participant-asana-task:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: self-hosted
    steps:
      - uses: psrenergy/asana-integration@master
        with:
          action: "add-participant"
          asana-secret: "${{ secrets.ASANA_SECRET }}"
          asana-workspace: "${{ secrets.ASANA_WORKSPACE }}"
          asana-project: "${{ secrets.ASANA_PROJECT }}"