name: edit-asana-task
on:
  issues:
    types: [edited, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

concurrency:
  group: asana-${{ github.event.issue.number }}

jobs:
  edit-asana-task:
    runs-on: self-hosted
    steps:
      - uses: psrenergy/asana-integration@master
        with:
          action: "edit"
          asana-secret: "${{ secrets.ASANA_SECRET }}"
          asana-workspace: "${{ secrets.ASANA_WORKSPACE }}"
          asana-project: "${{ secrets.ASANA_PROJECT }}"